packages:
  - 'packages/*'

catalog:
  # Build tools
  tsup: ^8.0.0
  typescript: ^5.9.3
  rimraf: ^5.0.0

  # Testing
  vitest: ^4.0.9
  '@vitest/ui': ^4.0.9
  '@testing-library/dom': ^10.4.1
  happy-dom: ^20.0.10
  jsdom: ^27.2.0

  # Linting & Formatting
  '@biomejs/biome': ^2.3.10
  prettier: ^3.6.2
  husky: ^9.1.7
  lint-staged: ^16.2.6

  # Release
  '@changesets/cli': ^2.29.7
