packages:
  - packages/*

catalog:
  '@biomejs/biome': ^2.3.10
  '@changesets/cli': 2.29.8
  '@testing-library/dom': ^10.4.1
  '@vitest/ui': ^4.0.9
  happy-dom: ^20.0.10
  husky: ^9.1.7
  jsdom: ^27.2.0
  lint-staged: ^16.2.6
  prettier: ^3.6.2
  rimraf: ^5.0.0
  tsup: ^8.0.0
  typescript: ^5.9.3
  vitest: ^4.0.9
